FROM alpine:3.14

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
    && apk update --no-cache && apk add --no-cache ca-certificates tzdata
ENV TZ Asia/Shanghai